export const SELECT_GENRE = 'SELECT_GENRE';
export const INVALID_GENRE = 'INVALID_GENRE';
export const REQUEST_FILMS = 'REQUEST_FILMS';
export const RECEIVE_FILMS = 'RECEIVE_FILMS';
export const ADD_FAVORITES = 'ADD_FAVORITES';
export const REMOVE_FAVORITES = 'REMOVE_FAVORITES';
